### ISSUE TITLE
Are you working on this still?

### ISSUE THREAD

**Issue by cy2k** [mjdescy/TodoTxtWin#1]
I've been using ToDoTxt.net for a long time, but I noticed your Mac version and it looks really nice from an interface perspective.  I was wondering if you're working on this Windows version and if it would be similar?

**Comment by mjdescy** [comment]
I haven't worked on this app in a long time. My iOS and Mac apps have been taking up all my programming time for about a year now. I would like to build this into a full app, but I'm not sure when I will get around to it.
